import { StyleSheet, Platform } from "react-native";

export const colors = {
  bg: "#070707",
  paper: "#fafaf8",
  ink: "#0a0a0a",
  inkSoft: "#161616",
  muted: "rgba(10,10,10,0.48)",
  dash: "rgba(26,26,26,0.55)",
};

export const mono = Platform.select({
  ios: "Courier",
  android: "monospace",
  default: "Courier New",
});

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  scroll: {
    flexGrow: 1,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 28,
  },
  paper: {
    maxWidth: 360,
    width: "100%",
    alignSelf: "center",
    backgroundColor: colors.paper,
    paddingHorizontal: 18,
    paddingTop: 26,
    paddingBottom: 30,
    borderRadius: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.45,
    shadowRadius: 20,
    elevation: 12,
  },
  headerMark: {
    textAlign: "center",
    fontSize: 13,
    opacity: 0.22,
    marginBottom: 4,
    color: colors.ink,
  },
  title: {
    fontFamily: mono,
    fontSize: 14,
    fontWeight: "700",
    fontStyle: "italic",
    letterSpacing: 2.8,
    textAlign: "center",
    textTransform: "uppercase",
    color: colors.ink,
    lineHeight: 19,
  },
  subtitle: {
    fontFamily: mono,
    fontSize: 8,
    fontWeight: "600",
    letterSpacing: 2,
    textAlign: "center",
    marginTop: 10,
    lineHeight: 14,
    opacity: 0.52,
    textTransform: "uppercase",
    color: colors.ink,
  },
  ref: {
    fontFamily: mono,
    fontSize: 8,
    textAlign: "center",
    marginTop: 10,
    opacity: 0.38,
    letterSpacing: 1.2,
    color: colors.ink,
  },
  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
    opacity: 0.82,
  },
  metaText: {
    fontFamily: mono,
    fontSize: 10,
    color: colors.ink,
    letterSpacing: 0.4,
  },
  dash: {
    fontFamily: mono,
    fontSize: 9,
    color: colors.dash,
    marginVertical: 14,
    letterSpacing: 0,
  },
  calloutWrap: {
    marginVertical: 16,
  },
  callout: {
    fontFamily: mono,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 2.2,
    textAlign: "center",
    lineHeight: 16,
    color: colors.ink,
    paddingHorizontal: 4,
  },
  secTitle: {
    fontFamily: mono,
    fontSize: 8,
    fontWeight: "700",
    letterSpacing: 2.5,
    marginTop: 20,
    marginBottom: 12,
    opacity: 0.48,
    textTransform: "uppercase",
    color: colors.ink,
  },
  body: {
    fontFamily: mono,
    fontSize: 10,
    lineHeight: 16,
    color: colors.inkSoft,
  },
  secHint: {
    fontFamily: mono,
    fontSize: 8,
    opacity: 0.42,
    letterSpacing: 1.6,
    marginBottom: 10,
    textTransform: "uppercase",
    color: colors.ink,
  },
  kvRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 7,
  },
  kvLabel: {
    fontFamily: mono,
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 1.2,
    opacity: 0.55,
    textTransform: "uppercase",
    color: colors.ink,
    flexShrink: 0,
  },
  kvValue: {
    fontFamily: mono,
    fontSize: 10,
    color: colors.ink,
    flex: 1,
    textAlign: "right",
    lineHeight: 14,
  },
  numLine: {
    flexDirection: "row",
    marginBottom: 9,
    paddingRight: 2,
  },
  numIdx: {
    fontFamily: mono,
    fontSize: 10,
    opacity: 0.38,
    width: 26,
    color: colors.ink,
  },
  numText: {
    fontFamily: mono,
    fontSize: 10,
    lineHeight: 15,
    color: colors.inkSoft,
    flex: 1,
  },
  link: {
    textDecorationLine: "underline",
    color: colors.ink,
  },
  barcode: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "flex-end",
    gap: 1,
    height: 32,
    marginTop: 14,
    opacity: 0.88,
  },
  bar: {
    backgroundColor: colors.ink,
  },
  stars: {
    fontFamily: mono,
    fontSize: 8,
    textAlign: "center",
    letterSpacing: 2,
    marginVertical: 14,
    opacity: 0.45,
    color: colors.ink,
  },
  ascii: {
    fontFamily: mono,
    fontSize: 9,
    lineHeight: 12,
    textAlign: "center",
    opacity: 0.72,
    color: colors.ink,
    marginVertical: 4,
  },
  footer: {
    fontFamily: mono,
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 1.6,
    textAlign: "center",
    lineHeight: 15,
    color: colors.ink,
    marginTop: 8,
  },
  footerSub: {
    fontWeight: "500",
    letterSpacing: 1.2,
    opacity: 0.55,
    marginTop: 4,
  },
});
